name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Запуск при пуше в main (можно поменять на нужную ветку)
  workflow_dispatch: # Ручной запуск

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t meph3/prime-check:v1.0 -t meph3/prime-check:latest .

      - name: Push Docker Image
        run: |
          docker push meph3/prime-check:v1.0
          docker push meph3/prime-check:latest
