name: CI/CD Prime-Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Build project
        run: ./build.sh

      - name: List files (debug)
        run: ls -la

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: prime-check-binary
          path: ./prime-check  # Путь к собранному бинарному файлу

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build  # Запускается только после успешного `build`

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: prime-check-binary
          path: ./  # Загружаем бинарный файл в текущую директорию

      - name: List files (debug)
        run: ls -la

      - name: Make binary executable
        run: chmod +x prime-check

      - name: Run tests
        run: ./test.sh

  package:
    name: Package
    runs-on: ubuntu-latest
    needs: test  # Запускается только после успешного `test`

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install packaging dependencies
        run: sudo apt-get update && sudo apt-get install -y dpkg-dev

      - name: Build .deb package
        run: ./package.sh

      - name: List package contents
        run: ls -la prime-check-deb/usr/local/bin/

      - name: Upload .deb package
        uses: actions/upload-artifact@v4
        with:
          name: prime-check-deb-package
          path: prime-check-deb/usr/local/bin/prime-check  # Проверяем, что файл существует!

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: package  # Запускается только после успешного `package`

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download .deb package
        uses: actions/download-artifact@v4
        with:
          name: prime-check-deb-package
          path: ./  # Загружаем в текущую директорию

      - name: Install Docker
        run: |
          curl -fsSL https://get.docker.com | sudo bash
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: Verify downloaded package
        run: ls -la ./prime-check  # Проверяем, загружен ли файл

      - name: Build Docker image
        run: docker build -t prime-check .

      - name: List Docker images
        run: docker images

      - name: Save Docker image
        run: docker save -o /tmp/prime-check.tar prime-check

      - name: Debug: List /tmp/ directory
        run: ls -la /tmp/

      - name: Upload Docker image
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: /tmp/prime-check.tar
