name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-package:
    runs-on: ubuntu-latest

    steps:
    - name: Клонирование репозитория
      uses: actions/checkout@v3

    - name: Установка зависимостей
      run: sudo apt update && sudo apt install -y build-essential

    - name: Разрешение на выполнение скриптов
      run: chmod +x build.sh test.sh package.sh

    - name: Сборка
      run: ./build.sh

    - name: Тестирование
      run: ./test.sh

    - name: Упаковка в deb
      run: ./package.sh

    - name: Загрузка артефактов (deb-пакет)
      uses: actions/upload-artifact@v4
      with:
        name: prime-check-deb
        path: prime-check_1.0_amd64.deb

    - name: Настройка Git перед созданием тега
      run: |
        git config --global user.email "your-email@example.com"
        git config --global user.name "GitHub Actions"

    - name: Создание тега (если его нет)
      run: |
        TAG_NAME="v1.0"
        if ! git rev-parse "$TAG_NAME" >/dev/null 2>&1; then
          git tag -a "$TAG_NAME" -m "Автоматический релиз $TAG_NAME"
          git push origin "$TAG_NAME"
        fi

    - name: Создание релиза
      uses: softprops/action-gh-release@v1
      with:
        files: prime-check_1.0_amd64.deb
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-and-push-docker:
    needs: build-test-package
    runs-on: ubuntu-latest

    steps:
    - name: Клонирование репозитория
      uses: actions/checkout@v3

    - name: Логин в GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Сборка Docker-образа
      run: |
        docker build -t ghcr.io/${{ github.repository }}/prime-check:latest .
    
    - name: Публикация Docker-образа
      run: |
        docker push ghcr.io/${{ github.repository }}/prime-check:latest
