name: CI/CD Prime Check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential dpkg-dev

      - name: Build project
        run: bash build.sh

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: prime-check-binary
          path: prime-check-deb/usr/local/bin/prime-check

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: prime-check-binary

      - name: Run tests
        run: bash test.sh

  package:
    name: Package
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Package into .deb
        run: bash package.sh

      - name: Upload .deb package
        uses: actions/upload-artifact@v4
        with:
          name: prime-check-deb-package
          path: prime-check-deb.deb

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: package

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download .deb package
        uses: actions/download-artifact@v4
        with:
          name: prime-check-deb-package
          path: build

      - name: Install Docker
        run: |
          curl -fsSL https://get.docker.com | sudo bash
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: Build and push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
          docker build -t meph3/prime-check:v1.0 .
          docker tag meph3/prime-check:v1.0 meph3/prime-check:latest
          docker push meph3/prime-check:v1.0
          docker push meph3/prime-check:latest
