name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v3

      - name: Установка зависимостей
        run: sudo apt-get update && sudo apt-get install -y curl jq

      - name: Проверка наличия Dockerfile
        run: |
          if [ ! -f Dockerfile ]; then
            echo "Ошибка: Dockerfile отсутствует!"
            exit 1
          fi

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Генерация тега версии
        run: |
          TAG_NAME="v1.0.$(date +%s)"
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

      - name: Сборка Docker-образа
        run: docker build -t meph3/prime-check:${{ env.TAG_NAME }} .

      - name: Публикация Docker-образа
        run: docker push meph3/prime-check:${{ env.TAG_NAME }}

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v3

      - name: Настройка Git перед созданием тега
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Проверка наличия тега
        id: check_tag
        run: |
          if git rev-parse "${{ env.TAG_NAME }}" >/dev/null 2>&1; then
            echo "tag_exists=true" >> $GITHUB_ENV
          else
            echo "tag_exists=false" >> $GITHUB_ENV
          fi

      - name: Создание тега (если его нет)
        if: env.tag_exists == 'false'
        run: |
          git tag -a "${{ env.TAG_NAME }}" -m "Автоматический релиз ${{ env.TAG_NAME }}"
          git push origin "${{ env.TAG_NAME }}"

      - name: Создание релиза
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: "Релиз ${{ env.TAG_NAME }}"
          draft: false
          prerelease: false
