name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-package:
    runs-on: ubuntu-latest

    steps:
    - name: Клонирование репозитория
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  

    - name: Установка зависимостей
      run: sudo apt update && sudo apt install -y build-essential

    - name: Разрешение на выполнение скриптов
      run: chmod +x build.sh test.sh package.sh

    - name: Сборка
      run: ./build.sh

    - name: Тестирование
      run: ./test.sh

    - name: Упаковка в deb
      run: ./package.sh

    - name: Загрузка артефактов (deb-пакет)
      uses: actions/upload-artifact@v4
      with:
        name: prime-check-deb
        path: prime-check_1.0_amd64.deb

    - name: Настройка Git перед созданием тега
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Удаление старого тега (если он существует)
      run: |
        TAG_NAME="v1.0"
        if git ls-remote --tags origin | grep -q "refs/tags/$TAG_NAME"; then
          echo "Старый тег $TAG_NAME найден. Удаляем..."
          git push origin --delete "$TAG_NAME"
          git tag -d "$TAG_NAME"
        fi

    - name: Создание нового тега
      run: |
        TAG_NAME="v1.0"
        git tag -a "$TAG_NAME" -m "Автоматический релиз $TAG_NAME"
        git push origin "$TAG_NAME"

    - name: Проверка наличия тега перед релизом
      run: |
        TAG_NAME="v1.0"
        if ! git ls-remote --tags origin | grep -q "refs/tags/$TAG_NAME"; then
          echo "Ошибка: Тег $TAG_NAME не найден после создания!"
          exit 1
        fi

    - name: Создание релиза
      uses: softprops/action-gh-release@v1
      with:
        tag_name: "v1.0"  
        files: prime-check_1.0_amd64.deb
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
