name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v3

      - name: Установка зависимостей
        run: sudo apt-get update && sudo apt-get install -y curl jq

      - name: Проверка наличия Dockerfile
        run: |
          if [ ! -f Dockerfile ]; then
            echo "Ошибка: Dockerfile отсутствует!"
            exit 1
          fi

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin



      - name: Сборка Docker-образа
        run: docker build -t meph3/prime-check:v1.0 .

      - name: Публикация Docker-образа
        run: docker push meph3/prime-check:v1.0

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v3

      - name: Настройка Git перед созданием тега
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Проверка наличия тега
        id: check_tag
        run: |
          TAG_NAME="v1.0"
          if git rev-parse "$TAG_NAME" >/dev/null 2>&1; then
            echo "Тег уже существует"
            echo "tag_exists=true" >> $GITHUB_ENV
          else
            echo "tag_exists=false" >> $GITHUB_ENV
          fi

      - name: Создание тега (если его нет)
        if: env.tag_exists == 'false'
        run: |
          TAG_NAME="v1.0"
          git tag -a "$TAG_NAME" -m "Автоматический релиз $TAG_NAME"
          git push origin "$TAG_NAME"

      - name: Создание релиза
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0
          name: "Релиз v1.0"
          draft: false
          prerelease: false
