name: CI/CD Prime Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Build project
        run: ./build.sh

      - name: List files (debug)
        run: ls -la prime-check-deb/usr/local/bin/

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: prime-binary
          path: prime-check-deb/usr/local/bin/prime-check  # Проверенный путь

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build  # Ждёт завершения build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: prime-binary
          path: ./  # Скачиваем бинарник в корень

      - name: List files (debug)
        run: ls -la

      - name: Make binary executable
        run: chmod +x prime-check

      - name: Run tests
        run: ./test.sh

  package:
    name: Package
    runs-on: ubuntu-latest
    needs: test  # Ждёт завершения тестов

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies for packaging
        run: sudo apt-get update && sudo apt-get install -y dpkg-dev

      - name: Package .deb file
        run: ./package.sh

      - name: List files (debug)
        run: ls -la prime-check-deb

      - name: Upload .deb package
        uses: actions/upload-artifact@v4
        with:
          name: prime-check-deb
          path: prime-check-deb  # Сохраняем deb-пакет

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: package  # Ждёт завершения packaging

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download .deb package
        uses: actions/download-artifact@v4
        with:
          name: prime-check-deb
          path: build/

      - name: List files (debug)
        run: ls -la build/

      - name: Build Docker Image
        run: docker build -t prime-check .

      - name: Save Docker image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: /tmp/prime-check.tar

      - name: Run Docker container
        run: docker run --rm prime-check
