name: CI/CD Prime-Check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Build project
        run: make all

      - name: List files (debug)
        run: ls -la

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: prime-check-binary
          path: ./prime-check  # Указываем путь к бинарному файлу

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: prime-check-binary

      - name: List files (debug)
        run: ls -la

      - name: Run tests
        run: |
          chmod +x test.sh
          ./test.sh

  package:
    name: Package
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install packaging dependencies
        run: sudo apt-get update && sudo apt-get install -y dpkg-dev

      - name: Build .deb package
        run: ./package.sh

      - name: List files (debug)
        run: ls -la prime-check-deb/

      - name: Upload .deb package
        uses: actions/upload-artifact@v4
        with:
          name: prime-check-deb-package
          path: prime-check-deb/usr/local/bin/prime-check

  docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: package

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download .deb package
        uses: actions/download-artifact@v4
        with:
          name: prime-check-deb-package
          path: .

      - name: Install Docker
        run: |
          curl -fsSL https://get.docker.com | sudo bash
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: Build Docker image
        run: docker build -t prime-check .

      - name: List Docker images
        run: docker images

      - name: Save Docker image
        run: docker save -o /tmp/prime-check.tar prime-check

      - name: Debug: List /tmp/ directory
        run: ls -la /tmp/

      - name: Upload Docker image
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: /tmp/prime-check.tar
